---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "remove dependencies that are no longer required"
    become: yes
    apt:
      autoremove: yes

  - name: "install nodejs and npm"
    become: yes
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: install pm2
    become: yes
    npm:
      name: pm2
      global: yes
      state: latest
      production: yes

  - name: extract artifact
    become: yes
    unarchive:
      src: ~/project/.circleci/ansible/roles/deploy/files/artifact.tar.gz
      dest: .

  - name: start app
    become: yes
    shell: |
      pm2 stop all
      pm2 start npm -- start